# Generated by Django 3.2.2 on 2021-05-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome', max_length=100)),
                ('telephone', models.CharField(help_text='Telefone', max_length=50)),
                ('address', models.CharField(help_text='Endereço', max_length=300)),
                ('email', models.CharField(help_text='Email', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome', max_length=100, unique=True)),
                ('value', models.FloatField(help_text='Valor')),
                ('length', models.CharField(default='P', help_text='P - Pequena, M - Média, G - Grande', max_length=1)),
                ('detail', models.CharField(help_text='Sabor ou qualquer outra informação.', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('value', models.FloatField()),
                ('status', models.CharField(default='P', help_text='P - Pendente, F - Finalizado', max_length=1)),
                ('clients', models.ManyToManyField(to='core.Client')),
                ('pizzas', models.ManyToManyField(to='core.Pizza')),
            ],
        ),
    ]
