# Generated by Django 3.2.3 on 2021-05-17 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0002_pizza_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='length',
        ),
    ]
